# Generated by Django 5.1.6 on 2025-03-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='album.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='album.subject'),
        ),
    ]
