# Generated by Django 5.1.6 on 2025-03-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_class_count_remove_student_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='album.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='count_teachers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
