# Generated by Django 5.1.6 on 2025-03-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_student_clas_alter_subject_count_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'get_latest_by': 'order_date'},
        ),
    ]
