# Generated by Django 5.1.6 on 2025-04-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_subject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['birthday', 'clas', 'surname', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['count_teachers', 'name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['subjects_count', 'surname', 'name']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_count',
            field=models.IntegerField(default=0),
        ),
    ]
